# Generated by Django 6.0.2 on 2026-03-07 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('map_link', models.CharField(blank=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('wifi', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
