# Generated by Django 6.0.2 on 2026-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='address',
            new_name='facilities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='city',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='rent',
            new_name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='Owner_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='test@gmail.com', upload_to='rooms/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='map_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Owner', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='owner_email',
            field=models.EmailField(default='text@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
