# Generated by Django 6.0.2 on 2026-02-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_address_room_facilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.AddField(
            model_name='room',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
