# Generated by Django 6.0.2 on 2026-02-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_facilities_room_ac_room_kitchen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner_email',
            new_name='Owner_email',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='owner_name',
            new_name='Owner_name',
        ),
    ]
