# Generated by Django 6.0.2 on 2026-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rename_owner_email_room_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='security',
            field=models.BooleanField(default=False),
        ),
    ]
